server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:./build/db/quotes
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        new_generator_mappings: false


logging:
  level:
    root: info
    ru.raiffeisen: info
    org.hibernate:
      stat: info
      cache: info
      engine.jdbc.spi.SqlExceptionHelper: error
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
